# Generated by Django 4.2.4 on 2023-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_User',
        ),
    ]
